// <auto-generated />
using Brewdogger.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Brewdogger.Api.Persistence.Migrations
{
    [DbContext(typeof(BrewdoggerDbContext))]
    [Migration("20181108043613_InitialDatabaseCreation")]
    partial class InitialDatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Brewdogger.Api.Entities.Beer", b =>
                {
                    b.Property<int>("BeerId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Abv");

                    b.Property<string>("BeerName");

                    b.Property<int>("BeerStyle");

                    b.Property<int>("Ibu");

                    b.HasKey("BeerId");

                    b.ToTable("Beers");

                    b.HasData(
                        new { BeerId = 1, Abv = 7.2, BeerName = "Hexagenia", BeerStyle = 3, Ibu = 80 },
                        new { BeerId = 2, Abv = 6.0, BeerName = "Pliny the Elder", BeerStyle = 4, Ibu = 100 },
                        new { BeerId = 3, Abv = 3.8, BeerName = "Coors Light", BeerStyle = 0, Ibu = 12 }
                    );
                });

            modelBuilder.Entity("Brewdogger.Api.Entities.Brewery", b =>
                {
                    b.Property<int>("BreweryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BreweryName");

                    b.Property<string>("City");

                    b.Property<string>("State");

                    b.HasKey("BreweryId");

                    b.ToTable("Breweries");
                });
#pragma warning restore 612, 618
        }
    }
}
