// <auto-generated />
using Brewdogger.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Brewdogger.Api.Persistence.Migrations
{
    [DbContext(typeof(BrewdoggerDbContext))]
    [Migration("20181119214825_ModifyIndicies")]
    partial class ModifyIndicies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Brewdogger.Api.Entities.Beer", b =>
                {
                    b.Property<int>("BeerId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Abv");

                    b.Property<string>("BeerName");

                    b.Property<string>("BeerStyle")
                        .IsRequired();

                    b.Property<int>("BreweryId");

                    b.Property<int>("Ibu");

                    b.HasKey("BeerId");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");

                    b.HasData(
                        new { BeerId = 1, Abv = 7.2, BeerName = "Hexagenia", BeerStyle = "Ipa", BreweryId = 1, Ibu = 80 },
                        new { BeerId = 2, Abv = 9.2, BeerName = "Widowmaker", BeerStyle = "DoubleIpa", BreweryId = 1, Ibu = 120 },
                        new { BeerId = 3, Abv = 5.5, BeerName = "Sierra Nevada Pale Ale", BeerStyle = "PaleAle", BreweryId = 2, Ibu = 75 }
                    );
                });

            modelBuilder.Entity("Brewdogger.Api.Entities.Brewery", b =>
                {
                    b.Property<int>("BreweryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BreweryName");

                    b.Property<string>("City");

                    b.Property<string>("State");

                    b.HasKey("BreweryId");

                    b.HasIndex("State");

                    b.ToTable("Breweries");

                    b.HasData(
                        new { BreweryId = 1, BreweryName = "Fall River Brewery", City = "Redding", State = "CA" },
                        new { BreweryId = 2, BreweryName = "Sierra Nevada Brewing Company", City = "Chico", State = "CA" }
                    );
                });

            modelBuilder.Entity("Brewdogger.Api.Entities.Beer", b =>
                {
                    b.HasOne("Brewdogger.Api.Entities.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
