// <auto-generated />
using Brewdogger.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Brewdogger.Api.Persistence.Migrations
{
    [DbContext(typeof(BrewdoggerDbContext))]
    partial class BrewdoggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Brewdogger.Api.Entities.Beer", b =>
                {
                    b.Property<int>("BeerId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Abv");

                    b.Property<string>("BeerName");

                    b.Property<string>("BeerStyle")
                        .IsRequired();

                    b.Property<int>("BreweryId");

                    b.Property<int>("Ibu");

                    b.HasKey("BeerId");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("Brewdogger.Api.Entities.Brewery", b =>
                {
                    b.Property<int>("BreweryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BreweryName");

                    b.Property<string>("City");

                    b.Property<string>("State");

                    b.HasKey("BreweryId");

                    b.HasIndex("State");

                    b.ToTable("Breweries");
                });

            modelBuilder.Entity("Brewdogger.Api.Entities.Beer", b =>
                {
                    b.HasOne("Brewdogger.Api.Entities.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
